---
- name: login to supertenant
  uri:
    url: "{{ okapi_login_url }}/authn/login"
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    body_format: json
    body: "{'username': '{{ superuser_username }}', 'password': '{{ superuser_password }}' }"
    status_code: 201, 404
  register: login_result
  listen: supertenant login

- name: Set Okapi token if supertenant is secured
  set_fact:
    supertenant_token: "{{ login_result['x_okapi_token'] }}"
  when: login_result.status is defined and login_result.status == 201
  listen: supertenant login

