---
# Ansible playbook to deploy Okapi and FOLIO modules
# Provision a host as a backend FOLIO system
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Bootstrap Python 3
      raw: test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python3-minimal)
      register: python3_output
      changed_when: python3_output.stdout != ""
    - name: Use Python 3 for Ansible
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

- hosts: all
  roles:
    - common
    - postgresql
    - docker-engine
    - okapi
    - kafka-zk

# Configure builds
# Need to build the webpack early to allow enough RAM for the build
# But don't want to register or enable modules at this point
- name: Configure testing build
  hosts: testing-core:testing
  roles:
    - role: stripes-build
      okapi_register_modules: false
      okapi_enable_modules: false
    - okapi-register-modules
    - tenant-data
    - okapi-tenant-deploy
    - create-tenant-admin
    - tenant-admin-permissions
    - set-patron-group

# Configure build for top-down deployment
# (Okapi dependency resolution)
- name: Configure snapshot build
  hosts: snapshot-core:snapshot
  roles:
    - role: stripes-build
      okapi_register_modules: false
      okapi_enable_modules: false
    - okapi-pull
    - tenant-data
    - role: build-module-list
      stripes_platform: /etc/folio/stripes
    - okapi-deployment
    - role: okapi-tenant-deploy
      create_db: no
      module_env: []
    - create-tenant-admin
    - tenant-admin-permissions
    - set-patron-group

- name: Configure release build
  hosts: release-core:release
  roles:
    - build-module-list
    - okapi-register-modules
    - tenant-data
    - okapi-tenant-deploy
    - create-tenant-admin
    - tenant-admin-permissions
    - set-patron-group

# Edge modules
- name: Set up Okapi to support edge modules
  hosts: testing
  roles:
    - role: okapi-register-modules
      folio_modules:
        - name: mod-oai-pmh
        - name: mod-rtac
        - name: edge-oai-pmh
        - name: edge-rtac
    - role: okapi-tenant-deploy
      folio_modules:
        - name: mod-oai-pmh
          deploy: yes
        - name: mod-rtac
          deploy: yes
        - name: edge-oai-pmh
        - name: edge-rtac
    - tenant-admin-permissions

- name: Set up edge modules
  hosts: testing:snapshot
  roles:
    - role: edge-module
      edge_module: edge-rtac
      edge_module_publish_port: 9700
      edge_module_path: /prod/rtac
      edge_module_expose_port: 8081
      edge_module_docker_env:
      auth_required: yes
      inst_user_perms:
        - rtac.all
    - role: edge-module
      edge_module: edge-oai-pmh
      edge_module_publish_port: 9701
      edge_module_path: /oai
      edge_module_expose_port: 8081
      edge_module_docker_env:
      auth_required: yes
      inst_user_perms:
        - oai-pmh.all

# Sample data for snapshot-core, testing, snapshot
- name: Load sample data for testing/snapshot builds
  hosts: snapshot-core:testing-core:testing:snapshot
  roles:
    - mod-inventory-mods

- name: Add sample users for permissions testing
  hosts: testing:snapshot:release
  roles:
    - add-users

# Set up stripes
- name: Build stripes webpack, assign permissions
  hosts: stripes-build
  roles:
    - role: stripes-build
      build_webpack: no
    - tenant-admin-permissions

- name: Build Stripes webpack and container, assign permissions
  hosts: stripes
  roles:
    - stripes-docker
    - tenant-admin-permissions

- name: Build Stripes container
  hosts: stripes-docker
  roles:
    - stripes-docker

# Roles for packaging
- hosts: vagrant
  tasks:
    - name: Install maven
      become: yes
      apt:
        name:
          - maven

- hosts: packer
  roles:
    - vagrant-tidy
