---
# Role to build the raml-module-builder framework
- name: Install prereqs
  become: yes
  apt:
    name:
      - git

- name: Clone raml-module-builder repository
  git: repo=https://github.com/folio-org/raml-module-builder.git dest={{ raml_module_builder_home }}
  register: raml_module_builder_clone

- name: Force Maven build if repository updated
  file: path={{ raml_module_builder_home }}/install.log state=absent
  when: raml_module_builder_clone.changed

- name: Build raml-module-builder
  shell: /usr/bin/mvn -q clean install > install.log
  args:
    chdir: "{{ raml_module_builder_home }}"
    creates: "{{ raml_module_builder_home }}/install.log"
