---
# Role to serve a stripes webpack via nginx

- name: Install nginx from apt
  become: yes
  apt: name=nginx

- name: Ensure nginx is running
  become: yes
  service: name=nginx state=started
  ignore_errors: yes

- name: disable nginx default vhost
  become: yes
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
    notify: Restart nginx

- name: Install edge module configuration for nginx
  become: yes
  template: src=edge.conf.j2 dest=/etc/nginx/sites-available/edge force=no
  notify: Restart nginx

- name: Link edge module configuration into sites-enabled
  become: yes
  file: src=/etc/nginx/sites-available/edge path=/etc/nginx/sites-enabled/edge state=link
  notify: Restart nginx

- meta: flush_handlers
