---
- wait_for: timeout=5

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      Content-Type: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  when: auth_required

# Configure reporting database connection info
- name: Configure mod-reporting DB settings
  uri:
    url: "{{ okapi_url }}/ldp/config/dbinfo"
    method: PUT
    body_format: json
    headers:
      Authtoken-Refresh-Cache: "true"
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
      Content-Type: application/vnd.api+json
    body: '{"key":"dbinfo","tenant":"{{ tenant }}","value":"{\"user\":\"{{ ldp_user }}\",\"url\":\"jdbc:postgresql://{{ pg_host }}:{{ pg_port }}/{{ ldp_db }}\",\"pass\":\"{{ ldp_password }}\"}"}'
    status_code: 200,422
  register: mod_reporting_config
  changed_when: mod_reporting_config.status == 200
