---
- name: Build tmp_folio_modules from stripes platform
  include_tasks: platform-build.yml
  when: stripes_platform is defined

- name: Get install JSON from URL for deployment
  uri:
    url: "{{ deploy_url }}"
    method: GET
    return_content: yes
  register: deploy_json
  when: stripes_platform is not defined and deploy_url|default(false)

- name: Convert deploy URL content to JSON if needed
  set_fact:
    deploy_json: "{{ deploy_json | combine( { 'json': deploy_json.content|from_json } ) }}"
  when: deploy_json|default(false) and deploy_json.json is not defined

- name: Get install JSON from file for deployment
  set_fact:
    deploy_json:
      json: "{{ lookup('file', deploy_file) }}"
  when: stripes_platform is not defined and deploy_file|default(false) and not deploy_url|default(false)

- name: Build list from deployment JSON
  set_fact:
    tmp_folio_modules: "{{ tmp_folio_modules|default([]) + [ { 'name': item.id|regex_replace('^(.*)-((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*).*)$','\\1'), 'version': item.id|regex_replace('^(.*)-((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*).*)','\\2'), 'deploy': true } ] if item.id|regex_search('-((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*).*)$') else tmp_folio_modules|default([]) + [ { 'name': item.id, 'deploy': true } ] }}"
  with_items: "{{ deploy_json.json }}"
  when: stripes_platform is not defined and deploy_json|default(false) and deploy_json.json is defined

- name: Get install JSON from URL for enabling modules (no deployment)
  uri:
    url: "{{ enable_url }}"
    method: GET
    return_content: yes
  register: enable_json
  when: stripes_platform is not defined and enable_url|default(false)

- name: Convert enable URL content to JSON if needed
  set_fact:
    enable_json: "{{ enable_json | combine( { 'json': enable_json.content|from_json } ) }}"
  when: enable_json|default(false) and enable_json.json is not defined

- name: Get install JSON from file for enabling modules (no deployment)
  set_fact:
    enable_json:
      json: "{{ lookup('file', enable_file) }}"
  when: stripes_platform is not defined and enable_file|default(false) and not enable_url|default(false)

- name: Build list from enabling modules JSON
  set_fact:
    tmp_folio_modules: "{{ tmp_folio_modules|default([]) + [ { 'name': item.id|regex_replace('^(.*)-((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*).*)$','\\1'), 'version': item.id|regex_replace('^(.*)-((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*).*)','\\2') } ] if item.id|regex_search('-((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*).*)$') else tmp_folio_modules|default([]) + [ { 'name': item.id } ] }}"
  with_items: "{{ enable_json.json }}"
  when: stripes_platform is not defined and enable_json|default(false) and enable_json.json is defined

- name: Combine with existing folio_modules list for custom settings
  set_fact:
    tmp_folio_modules_combined: "{{ tmp_folio_modules_combined|default([]) + [ item|combine(folio_modules|default([])|selectattr('name','equalto',item.name)|first|default({})) ] }}"
  with_items:
    - "{{ tmp_folio_modules }}"

- name: Reset folio_modules
  set_fact:
    folio_modules: "{{ tmp_folio_modules_combined }}"
