
- name: set minimum ES kernel requirement for vm.max_map_count
  become: yes
  sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes
    state: present
    reload: yes
  when: folio_install_type == "single_server"

- name: launch elasticsearch container
  docker_container:
    name: elasticsearch
    image: "{{ elasticsearch_image }}:{{ elasticsearch_image_tag }}"
    env:
      ELASTICSEARCH_EXTRA_FLAGS: -Ediscovery.type=single-node
      ELASTICSEARCH_HEAP_SIZE: "{{ jvm_heap_size }}"
      ELASTICSEARCH_PLUGINS: analysis-icu,analysis-kuromoji,analysis-smartcn,analysis-nori,analysis-phonetic
    memory: "{{ elasticsearch_memory_limit }}"
    volumes:
      - "/usr/share/elasticsearch/data"
    ports:
      - "{{ elasticsearch_host_rest_port }}:9200"
      - "{{ elasticsearch_host_node_port }}:9300"
    restart: yes
  become: yes
  when: folio_install_type == "single_server"

- name: check if elasticseach launched properly
  uri:
    url: "http://localhost:{{ elasticsearch_host_rest_port }}/_cluster/health"
    status_code: 200
  register: elasticsearch_status_check
  retries: 20
  delay: 5
  until: elasticsearch_status_check is not failed
  when: folio_install_type == "single_server"
