# -*- mode: ruby -*-
# vi: set ft=ruby :
# Build a VM to serve as an Okapi/Docker server
# Deploy development environment

Vagrant.configure(2) do |config|
  # Target platform is Debian/jessie on VirtualBox
  config.vm.box = "mod-users-demo"
  config.vm.box_url = "ftp://tekka.indexdata.com/pub/folio-vagrant/mod-users-demo.box"
  config.vm.box_download_checksum = "ec501fde2a20fda915b811a76d8e102a"
  config.vm.box_download_checksum_type = "md5"

  # Give us a little headroom
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 9130, host: 9130

end

