---
# defaults file for module-kubernetes

namespace: default
kubeconfig: ~/.kube/config

# Okapi Variables from Anisble Role: okapi_kubernetes
pg_host: localhost
pg_port: 5432
okapi_url: http://okapi:9130

# New Varibles for this ROLE
# Backend Modules
module_list:
  - mod-users-15.7.0-SNAPSHOT.85

# Mod descriptor registry
folio_registry: http://folio-registry.dev.folio.org
folio_options_url: https://raw.githubusercontent.com/folio-org/folio-ansible/master/group_vars/snapshot
# DB connection
pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_maint_db: postgres
db_database: okapi
db_maxpoolsize: 20
db_password: password
db_username: folio_admin
kafka_host: kafka
kafka_port: 9092
kafka_port_2: 9093

# Kubernetes Secret Names for Backend Module DB and Kafka ENV
db_secret_name: db-connect
kafka_secret_name: kafka-connect

# Services
service_type: ClusterIP

# Set to present or absent
# Create or clean up State
k8s_state: present

# Optional tasks
create_db: yes
create_secret: yes
okapi_pull: yes

# set to true for deployment of pr preview module
preview: false

# Edge Secure Store (Ephemeral, Vault)
edge_secure_store: Ephemeral
edge_secret_name: edge-properties
edge_volume_name: edge-volume

# Common Edge Modules Configs
# Ephemiral
institutional_users:
  - username: test
    password: test1234
    tenant: diku

# Vault
vault_token: default-token
vault_addr: http://vault.vault.svc.cluster.local:8200


#Both variables below use to mount volume and specify file.
edge_mount_path: /mnt
edge_secure_store_props: "{{ edge_mount_path }}/{{ edge_secure_store | lower }}.properties"

folio_modules:
  - name: "edge-rtac"
  - version: "2.0.2"
  - deploy: true
